CREATE DATABASE IF NOT EXISTS oophp;

USE oophp;

GRANT ALL ON oophp.* TO user@localhost IDENTIFIED BY "pass";

SET NAMES utf8;

DROP TABLE IF EXISTS `users`;

CREATE TABLE `users`
(
  `id` INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100)
) ENGINE INNODB CHARACTER SET utf8 COLLATE utf8_swedish_ci;

SELECT * FROM users
